### COMP5339 Assignment 1
#### Student ID: 540666979
#### Student ID: 540800919

In [1]:
import pandas as pd
import numpy as np
import requests
import json
import time
import googlemaps
from tqdm.notebook import tqdm
from bs4 import BeautifulSoup
from io import BytesIO, StringIO

#### General Data Acquisition Methods

In [2]:
#web scraping general function
def get_html(url):
    webpage = requests.get(url).text
    content = None
    if webpage != None:
        content = BeautifulSoup(webpage, 'html.parser')
    return content

#get response from a url
def get_response(url):
    while True:
        try:
            response = requests.get(url)
            if response.text != None:
                return response.text
        except:
            print("Failure in connection")

#### Setting up database method

In [3]:
#general database functions
import duckdb

def open_connection():
    while True:
        conn = duckdb.connect(database=':memory:')
        try:
            conn.execute("LOAD spatial")
            break
        except Exception as e:
            print("unable to load spatial")
            conn.execute("INSTALL spatial")
            continue
    return conn
conn = open_connection()

### Data Acquisition

In [4]:
#web scraping cer
def find_cer_dataset(url, base_url, options):
    soup = get_html(url)
    csv_paths = []
    for item in soup.find_all('div', 'vue-datavis-wrapper'):
        for sub_item in  item.find_all('div', 'cer-accordion__body'):
            a = sub_item.find(
                'a', 
                href=lambda x:x and any(opt in x for opt in options))
            if a:
                csv_paths.append(base_url + a['href'])
    return csv_paths

def get_datasets(csv_paths):
    power_dfs = []
    for path in csv_paths:
        csv_response = get_response(path)
        df = pd.read_csv(StringIO(csv_response))
        power_dfs.append(df)
    return power_dfs

In [5]:
#web scraping abs
def load_excel(file_link):
    file_response = requests.get(file_link)
    file_bytes = BytesIO(file_response.content)
    return pd.ExcelFile(file_bytes)
    
def find_abs_dataset(url, base_url, needle):
    soup = get_html(url)
    contents = soup.find_all('li', 'field__item')
    file_link = None
    for item in contents:
        h4 = item.find('h4')
        if needle in h4:
            a = item.find('a', href=True)
            if a:
                file_link = base_url + a['href']
                return file_link
                
def load_abs():
    file_url = find_abs_dataset(ECO_URL, ABS_PAGE_URL, TITLE_NEEDLE)
    xls = load_excel(file_url)
    return xls

In [6]:
urls = {2023: "https://api.cer.gov.au/datahub-public/v1/api/ODataDataset/NGER/dataset/ID0243?select%3D%2A"}
year = 2014
for i in range(75,84):
    urls[year] = f"https://api.cer.gov.au/datahub-public/v1/api/ODataDataset/NGER/dataset/ID00{i}?select%3D%2A"
    year += 1

NGER_14_24 = []
idx = 0
for year in urls:
    content = json.loads(get_response(urls[year]))
    df = pd.DataFrame(content)
    df['year'] = year
    NGER_14_24.append(df)
    idx += 1
    time.sleep(2)

In [7]:
PS_URL = "https://cer.gov.au/markets/reports-and-data/large-scale-renewable-energy-data"
CER_PAGE_URL = "https://cer.gov.au"
station_options = {'accredited', 'committed', 'probable'}
power_station_paths = find_cer_dataset(PS_URL, CER_PAGE_URL, station_options)
power_dfs = get_datasets(power_station_paths)

In [8]:
ECO_URL = "https://www.abs.gov.au/methodologies/data-region-methodology/2011-24#data-downloads"
ABS_PAGE_URL = "https://www.abs.gov.au"
TITLE_NEEDLE = "Economy and industry, ASGS and LGA, 2011, 2016-2024"

abs_xls = load_abs()
abs_xls

### NGER Dataset: Cleaning and Integration

In [9]:
#NGER datasets integration and cleaning
def nger_integration(dfs):
    if not dfs:
        raise ValueError("NGER_14_24 is empty")
    ref = dfs[-1]
    standard_cols = ref.columns.tolist()

    aligned = []
    for df in dfs:
        df = df.copy()
        src_cols = df.columns.tolist()
        k = min(len(src_cols), len(standard_cols))
        if k:
            df = df.rename(columns=dict(zip(src_cols[:k], standard_cols[:k])))
        df = df.reindex(columns=standard_cols)
        aligned.append(df)
    combined = pd.concat(aligned, ignore_index=True, sort=False)
    return combined

def nger_cleaning(df, standard_cols):
    NGER = df.copy()
    numeric_cols = [   
        "totalscope1emissionstCO2e",
        "totalscope2emissionstCO2e",
        "totalemissionstCO2e",
        "electricityproductionMWh",
        "electricityproductionGJ",
        "emissionintensitytCO2eMWh"
    ]
    mask = pd.Series(True, index=NGER.index)
    if "facilityname" in NGER.columns:
        mask &= (NGER['facilityname'] != 'Corporate Total')
    if 'type' in NGER.columns:
        mask &= NGER["type"].notna() & (NGER["type"] != "-")

    if "electricityproductionGJ" in NGER.columns:
        mask &= NGER["electricityproductionGJ"].notna()

    NGER = NGER[mask].copy()
    
    for col in ["totalscope1emissionstCO2e", "totalscope2emissionstCO2e"]:
        if {"year", col}.issubset(NGER.columns):
            NGER[col] = NGER.groupby("year")[col].transform(lambda s: s.fillna(s.median()))


    parameters = {"emissionintensitytCO2eMWh", "totalemissionstCO2e", "electricityproductionMWh"}
    if parameters.issubset(NGER.columns):
        m = NGER["emissionintensitytCO2eMWh"].isna() & (NGER["electricityproductionMWh"] > 0)
        NGER.loc[m, "emissionintensitytCO2eMWh"] = (
            NGER.loc[m, "totalemissionstCO2e"] / NGER.loc[m, "electricityproductionMWh"]
        )
    if "gridconnected" in NGER.columns:
        NGER["gridconnected"] = NGER["gridconnected"].fillna("Off").replace("-", "Off")
    if "grid" in NGER.columns:
        NGER["grid"] = NGER["grid"].fillna("Off-grid").replace("-", "Off-grid")
    NGER = NGER.drop(columns=["importantnotes"], errors="ignore")
    keys = ['year', 'facilityname']
    if keys:
        numeric_cols = NGER.select_dtypes(include='number').columns.difference(keys)
        non_numeric_cols = [c for c in NGER.columns if c not in set(numeric_cols).union(keys)]
        agg = {**{c: "first" for c in non_numeric_cols}, **{c: "mean" for c in numeric_cols}}
        NGER = (
            NGER
            .groupby(keys, as_index=False, dropna=False)
            .agg(agg)
        )
    
    ordered = []
    ordered += [c for c in keys if c in NGER.columns]
    ordered += [c for c in standard_cols if c in NGER.columns and c not in ordered]
    ordered += [c for c in NGER.columns if c not in ordered]
    NGER = NGER.loc[:, ordered]
    return NGER

### NGER Dataset: Loading into Database

In [10]:
#NGER dataset transformation and loading into database
def create_nger_schema(df):
    conn.execute("DROP TABLE IF EXISTS nger_fact_table")
    conn.execute("DROP TABLE IF EXISTS nger_dim_table")
    conn.execute("DROP SEQUENCE IF EXISTS nger_id_seq")
        
    conn.execute("CREATE SEQUENCE nger_id_seq START 1")

    conn.execute("""
        CREATE TABLE nger_dim_table (
            entity_id INTEGER DEFAULT nextval('nger_id_seq'),
            reportingentity VARCHAR NOT NULL,
            facilityname VARCHAR NOT NULL,
            type VARCHAR NOT NULL,
            state VARCHAR NOT NULL,
            grid VARCHAR NOT NULL,
            gridconnected VARCHAR NOT NULL,
            primaryfuel VARCHAR NOT NULL,
            year BIGINT NOT NULL,
            PRIMARY KEY (entity_id)
        )
    """)

    conn.execute("""
        CREATE TABLE nger_fact_table (
            entity_id INTEGER PRIMARY KEY,
            electricityproductionGJ FLOAT NOT NULL,
            electricityproductionMWh FLOAT NOT NULL,
            emissionintensitytCO2eMWh FLOAT NOT NULL,
            totalemissionstCO2e FLOAT NOT NULL,
            totalscope1emissionstCO2e FLOAT NOT NULL,
            totalscope2emissionstCO2e FLOAT NOT NULL,
            FOREIGN KEY (entity_id) REFERENCES nger_dim_table(entity_id)
        )
    """)

    dim_cols = ['reportingentity', 'facilityname', 'type', 
               'state', 'grid', 'gridconnected', 'primaryfuel', 'year']
    nger_dim_df = df[dim_cols].drop_duplicates().reset_index(drop=True)
    conn.register("nger_dim_df", nger_dim_df)
    
    conn.execute("""
        INSERT INTO nger_dim_table (
            reportingentity, facilityname, type, 
            state, grid, gridconnected, primaryfuel, year)
        SELECT reportingentity, facilityname, type, state, 
               grid, gridconnected, primaryfuel, year 
        FROM nger_dim_df
    """)

    nger_dim_table = conn.execute("SELECT * FROM nger_dim_table").fetchdf()
    nger_fact_df = df.merge(nger_dim_table, on=dim_cols,
                            how='inner')
    nger_fact_df = (
        df.merge(nger_dim_table, on=dim_cols, how='inner')
          .loc[:, ['entity_id'] + [c for c in df.columns if c not in dim_cols]]
    )
    conn.register("nger_fact_df", nger_fact_df)
    print(nger_fact_df.columns.tolist())
    conn.execute("""
    INSERT INTO nger_fact_table (
        entity_id,
        electricityproductionGJ, electricityproductionMWh,
        emissionintensitytCO2eMWh, totalemissionstCO2e,
        totalscope1emissionstCO2e, totalscope2emissionstCO2e
    )
    SELECT * FROM nger_fact_df
    """)
    return "Successfully Create the NGER fact table and dimension table"

In [11]:
NGER = nger_integration(NGER_14_24)
NGER = nger_cleaning(NGER, NGER.columns.tolist())
create_nger_schema(NGER)
conn.execute("SELECT * FROM nger_dim_table LIMIT 5").df()

['entity_id', 'electricityproductionGJ', 'electricityproductionMWh', 'totalscope1emissionstCO2e', 'totalscope2emissionstCO2e', 'totalemissionstCO2e', 'emissionintensitytCO2eMWh']

,entity_id,reportingentity,facilityname,type,state,grid,gridconnected,primaryfuel,year
0,1,ELECTRICITY GENERATION AND RETAIL CORPORATION,Albany Wind Farm,F,WA,SWIS,On,Wind,2014
1,2,LMS ENERGY PTY LTD,Albury Renewable Energy Facility,F,NSW,NEM,On,Landfill Gas,2014
2,3,MOMENTUM ENERGY PTY LIMITED,Alfred Hospital Cogeneration Plant,F,VIC,NEM,On,Gas,2014
3,4,ALCOA AUSTRALIAN HOLDINGS PTY LTD,Alinta Pinjarra Generation Facility,F,WA,SWIS,On,Gas,2014
4,5,ALCOA AUSTRALIAN HOLDINGS PTY LTD,Alinta Wagerup Generation Facility,F,WA,SWIS,On,Gas/Diesel,2014

### CER Dataset: Integration and Cleaning

In [12]:
def cer_integration(power_dfs):
    ac, cm, pr = power_dfs
    rename_map =  {
        "Power station name": "Project Name",
        "Installed capacity (MW)": "MW Capacity",
        "Fuel Source (s)": "Fuel Source",
        "State": "State",
        "State ": "State"  
    }
    
    def standardize(df, status):
        df = df.rename(columns=rename_map)
        df = df[["Project Name", "State", "MW Capacity", "Fuel Source"]].copy()
        df["status"] = status
        return df
    ac_core = standardize(ac, "accredited")
    cm_core = standardize(cm, "committed")
    pr_core = standardize(pr, "probable")

    return pd.concat([ac_core, cm_core, pr_core], ignore_index=True)

def cer_cleaning(df, export = True):
    df = df.apply(lambda col: col.str.strip() if col.dtype == "object" else col)
    df["Project Name"] = df["Project Name"].str.split("-").str[0].str.strip()
    keys = ['Project Name', 'State']
    dupmask = df.duplicated(keys, keep=False)
    duplicates = df.loc[dupmask].sort_values(keys)
    #aggregate duplicates
    numeric_cols = df.select_dtypes(include="number").columns.difference(keys)
    non_numeric_cols = df.columns.difference(numeric_cols.union(keys))
    agg_rules = {**{col: "first" for col in non_numeric_cols},
                 **{col: "mean" for col in numeric_cols}}
    df_clean = df.groupby(keys, as_index=False).agg(agg_rules)
    if export:
        df_clean.to_csv("core_summary.csv", index=False)
    return df_clean
core_summary = cer_integration(power_dfs)
core_summary = cer_cleaning(core_summary)
core_summary.head()

,Project Name,State,Fuel Source,status,MW Capacity
0,123 Sippy Downs,QLD,Solar,accredited,0.200
1,AFS Cadell Balranald,NSW,Solar,accredited,4.827
2,ATCO Gas Australia Jandakot Microgrid,WA,Solar,accredited,0.301
3,AU186 Oakdale West 5B,NSW,Solar,accredited,0.150
4,AU254 M7 BH,NSW,Solar,accredited,0.438

### CER Dataset: Augmenting the Spatial Data of the power Station with the Dataset

In [13]:
# data augmentation
gmaps = googlemaps.Client(key="AIzaSyAl7LWzK05ZLBkzDAyonAj5OSew3IwV_1E")

def get_coordinates_google(address):
    try:
        geocode_result = gmaps.geocode(address)
        if geocode_result:
            location = geocode_result[0]['geometry']['location']
            lat = location['lat']
            lon = location['lng']

            region = None
            for comp in geocode_result[0]['address_components']:
                if "locality" in comp['types']:
                    region = comp['long_name']
                    break

            return lat, lon
    except Exception as e:
        print(f"Error on {address}: {e}")
    return None, None, None

In [14]:
def geocode_projects(core_summary, sleep=0.025):
    latitudes, longitudes, regions = [], [], []

    for addr in tqdm(core_summary["Project Name"] + ", " +
                     core_summary["State"] + ", Australia",
                     desc="Google Geocoding", unit="site"):
        lat, lon = get_coordinates_google(addr)
        latitudes.append(lat)
        longitudes.append(lon)
        time.sleep(sleep)
        

    core_summary = core_summary.copy()
    core_summary["latitude"] = latitudes
    core_summary["longitude"] = longitudes

    return core_summary

def validate_spatial_values(core_summary, sleep=0.025):
    df = core_summary.copy()
    validate = []
    valid = 0
    for lat, lon, validate_state in tqdm(zip(df['latitude'], df['longitude'], df['State']),
                                         total=len(df), desc='Validating', unit='site'):
        try:
            results = gmaps.reverse_geocode((lat, lon))
            matched = any(
                any(comp.get("short_name") == validate_state
                    for comp in r.get("address_components", []))
                for r in results
            )

            if matched:
                valid += 1
        except Exception:
            validate.append(False)
        finally:
            time.sleep(sleep)
    return valid / len(core_summary)*100

In [15]:
core_summary = geocode_projects(core_summary)
core_summary.to_csv("core_summary_with_google_coords.csv", index=False)

Google Geocoding:   0%|          | 0/357 [00:00<?, ?site/s]

In [16]:
core_summary.head()

,Project Name,State,Fuel Source,status,MW Capacity,latitude,longitude
0,123 Sippy Downs,QLD,Solar,accredited,0.200,-26.713970,153.061791
1,AFS Cadell Balranald,NSW,Solar,accredited,4.827,-34.720958,143.498993
2,ATCO Gas Australia Jandakot Microgrid,WA,Solar,accredited,0.301,-32.114441,115.858566
3,AU186 Oakdale West 5B,NSW,Solar,accredited,0.150,-34.079936,150.508574
4,AU254 M7 BH,NSW,Solar,accredited,0.438,-33.837840,150.856227

In [ ]:
print("% of valid locations found by the Geocoding API", validate_spatial_values(core_summary))

Validating:   0%|          | 0/357 [00:00<?, ?site/s]

In [ ]:
core_summary.head()

### CER Dataset: Loading Dataset to Database

In [ ]:
#CER dataset transformation and loading into database
def create_powerStation_schema(df):
    for table in ['powerStation_fact_table', 'powerStation_dim_table']:
        conn.execute(f"DROP TABLE IF EXISTS {table}")
    for seq in ['station_id_seq']:
        conn.execute(f"DROP SEQUENCE IF EXISTS {seq}")
    conn.execute("CREATE SEQUENCE station_id_seq START 1")
    
    conn.execute("""
    CREATE TABLE powerStation_dim_table (
        station_id INTEGER DEFAULT nextval('station_id_seq'),
        projectName VARCHAR NOT NULL,
        state VARCHAR NOT NULL,
        fuel_source VARCHAR NOT NULL,
        status VARCHAR NOT NULL,
        UNIQUE(projectName, state),
        PRIMARY KEY (station_id)
    )
    """)
    
    conn.execute("""
    CREATE TABLE powerStation_fact_table (
        station_id INTEGER,
        mw_capacity DOUBLE,
        location GEOMETRY,
        FOREIGN KEY (station_id) REFERENCES powerStation_dim_table (station_id),
        PRIMARY KEY (station_id)
    )
    """)

    dim_cols = ['Project Name', 'State', 'Fuel Source', 'status']
    dim_df = df[dim_cols].drop_duplicates().reset_index(drop=True)

    conn.register("powerStation_dim_df", dim_df)
    conn.execute("""
        INSERT INTO powerStation_dim_table (projectName, state, fuel_source, status) 
        SELECT * FROM powerStation_dim_df
    """)

    dim_table = conn.execute("SELECT * FROM powerStation_dim_table").fetchdf()
    powerStation_fact_df = df.merge(
        dim_table,
        left_on=['Project Name', 'State'],
        right_on=['projectName', 'state'],
        how='inner'
    )

    powerStation_fact_df = powerStation_fact_df[['station_id', 'MW Capacity', 'longitude', 'latitude']]
    powerStation_fact_df.rename(columns={"MW Capacity": "mw_capacity"}, inplace=True)
    conn.register("powerStation_fact_df", powerStation_fact_df)
    print(powerStation_fact_df.columns)
    conn.execute("""
        INSERT INTO powerStation_fact_table (station_id, mw_capacity, location)
        SELECT station_id, mw_capacity, ST_Point2D(longitude, latitude)
        FROM powerStation_fact_df
    """)
    
    return "Successfully created PowerStation fact and dimension tables with spatial location in fact table."

In [ ]:
create_powerStation_schema(core_summary)
conn.execute("SELECT * FROM powerStation_fact_table LIMIT 5").fetchdf()

In [ ]:
core_summary

### ABS Economy Dataset: Integration and Cleaning

In [ ]:
#ABS Dataset integration and cleaning
eco_df = pd.read_excel(abs_xls, sheet_name = abs_xls.sheet_names[1], 
                        skiprows=5, header=[0,1], index_col=[0,1,2], na_values=['-'])[:29090]
headers = eco_df.columns.get_level_values(0).unique()
abs_df = eco_df['Number of businesses by industry - at 30 June']

def economy_table_cleaning(table):
    try:
        df = table.copy()
        df.reset_index(inplace=True)
        df.rename(columns={'level_0':'Code', 'level_1':'Region', 'level_2':'Year'}, inplace=True)
        df.set_index(['Code', 'Region', 'Year'], inplace=True)
        df = df[~(df.isna().all(axis=1) & (df.index.get_level_values('Year') < 2020))]
        df.reset_index(inplace=True)
        df = df.rename_axis(columns=[None, None] if isinstance(df.columns, pd.MultiIndex) else [None])
        df.set_index(['Code', 'Region'], inplace=True)
        df = df.groupby(level=['Code', 'Region']).transform(
                    lambda x: x.ffill().fillna(0).bfill()
                )
        df.reset_index(inplace=True)
        for col in df.columns:
            if '(no.)' in col or 'number' in col or 'Number' in col:
                df[col] = df[col].astype('int64')
        table = df

    except Exception as e:
            print("Data is either already cleaned/invalid")
            
    return table

In [ ]:
abs_df = economy_table_cleaning(abs_df)
abs_df.head()

### ABS Economy Dataset: Loading into Database

In [ ]:
#ABS Dataset: Loading into Database
#database schema for the abs table
def create_abs_schema(df):
    for table in ['abs_fact_table', 'abs_dim_table']:
        conn.execute(f"DROP TABLE IF EXISTS {table}")
    for seq in ['report_id_seq']:
        conn.execute(f"DROP SEQUENCE IF EXISTS {seq}")
    conn.execute("CREATE SEQUENCE report_id_seq START 1")
    
    conn.execute("""
    CREATE TABLE abs_dim_table (
        report_id INTEGER DEFAULT nextval('report_id_seq'),
        code VARCHAR,
        region VARCHAR,
        year BIGINT,
        PRIMARY KEY (report_id)
    )
    """)
    
    conn.execute("""
    CREATE TABLE abs_fact_table (
        report_id INTEGER,
        agriculture BIGINT NOT NULL DEFAULT 0,
        mining BIGINT NOT NULL DEFAULT 0,
        manufacturing BIGINT NOT NULL DEFAULT 0,
        elec_gas_water BIGINT NOT NULL DEFAULT 0,
        construction BIGINT NOT NULL DEFAULT 0,
        wholesale BIGINT NOT NULL DEFAULT 0,
        retail BIGINT NOT NULL DEFAULT 0,
        accom_food BIGINT NOT NULL DEFAULT 0,
        transport BIGINT NOT NULL DEFAULT 0,
        information_media BIGINT NOT NULL DEFAULT 0,
        finance BIGINT NOT NULL DEFAULT 0,
        rental BIGINT NOT NULL DEFAULT 0, 
        sci_tech BIGINT NOT NULL DEFAULT 0,
        admin BIGINT NOT NULL DEFAULT 0,
        public_admin BIGINT NOT NULL DEFAULT 0,
        education BIGINT NOT NULL DEFAULT 0,
        health_care BIGINT NOT NULL DEFAULT 0,
        arts BIGINT NOT NULL DEFAULT 0,
        others BIGINT NOT NULL DEFAULT 0,
        unknown BIGINT NOT NULL DEFAULT 0,
        PRIMARY KEY (report_id),
        FOREIGN KEY (report_id) REFERENCES abs_dim_table (report_id)
    )
    """)
    
    abs_dim_df = df[['Code', 'Region', 'Year']].drop_duplicates().reset_index(drop=True)
    conn.register("vr_abs_dim_df", abs_dim_df)
    conn.execute("""
        INSERT INTO abs_dim_table (code, region, year)
        SELECT Code, Region, Year FROM vr_abs_dim_df
    """)

    abs_dim_table = conn.execute("SELECT * FROM abs_dim_table").fetchdf()
    abs_fact_df = df.merge(abs_dim_table, left_on=['Code', 'Region', 'Year'],
                           right_on=['code', 'region', 'year'], how='inner')
    df_cols = ['report_id'] + list(df.columns[3:])
    abs_fact_df = abs_fact_df[df_cols]
    conn.register("vr_abs_fact_df", abs_fact_df)
    conn.execute("""
    INSERT INTO abs_fact_table (
        report_id,
        agriculture, mining, manufacturing, elec_gas_water,
        construction, wholesale, retail, accom_food,
        transport, information_media, finance, rental,
        sci_tech, admin, public_admin, education,
        health_care, arts, others, unknown
    )
    SELECT * FROM abs_fact_df
    """)
    return "Successfully Create the ABS Economy fact table and dimension table"

In [ ]:
create_abs_schema(abs_df)
conn.execute("SELECT * FROM abs_fact_table LIMIT 5").fetchdf()

### Exploratory Data Analysis for the CER Power Station Dataset (Our dataset of interest)

In [ ]:
import matplotlib.pyplot as plt

sql = """
SELECT
  d.state AS state,
  SUM(CAST(f.mw_capacity AS DOUBLE)) AS mw_capacity
FROM powerStation_fact_table f
JOIN powerStation_dim_table  d USING (station_id)
WHERE f.mw_capacity IS NOT NULL
GROUP BY 1
ORDER BY 2
"""

mw_by_state = conn.execute(sql).fetchdf().set_index("state")["mw_capacity"]

plt.figure(figsize=(8, 5))
mw_by_state.plot(kind="barh", color="teal")
plt.title("Total Renewable Power Station Capacity by State")
plt.xlabel("Total MW Capacity")
plt.ylabel("State")
plt.tight_layout()
plt.show()

In [ ]:
sql = """
SELECT
  CAST(f.mw_capacity AS DOUBLE) AS mw_capacity,
  ST_X(f.location) AS longitude,
  ST_Y(f.location) AS latitude
FROM powerStation_fact_table f
JOIN powerStation_dim_table  d USING (station_id)
WHERE f.location IS NOT NULL
  AND f.mw_capacity IS NOT NULL
  AND f.mw_capacity > 0
"""

df = conn.execute(sql).fetchdf()
df = df[
    df["longitude"].between(110, 155)
    & df["latitude"].between(-45, -10)
].dropna(subset=["longitude", "latitude", "mw_capacity"])

vmin = df["mw_capacity"].quantile(0.05)
vmax = df["mw_capacity"].quantile(0.95)

plt.figure(figsize=(8, 6))
sc = plt.scatter(
    df["longitude"], df["latitude"],
    c=df["mw_capacity"],
    cmap="plasma",
    s=30,
    alpha=0.7,
    vmin=vmin,
    vmax=vmax
)
plt.colorbar(sc, label="MW Capacity")
plt.title("Spatial Distribution of Renewable Power Stations")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.tight_layout()
plt.show()

In [ ]:
conn.close()